# Generated by Django 6.0.3 on 2026-04-05 07:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.CharField(blank=True, db_index=True, max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('uploaded_media', models.JSONField(blank=True, default=dict, help_text='Map field_key -> media file URL')),
                ('primary_color', models.CharField(blank=True, max_length=20)),
                ('secondary_color', models.CharField(blank=True, max_length=20)),
                ('is_completed', models.BooleanField(default=False, help_text='User has finalized their demo session')),
                ('converted_to_order', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_sessions', to='catalog.templateitem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomizerMediaUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=100)),
                ('file', models.ImageField(upload_to='customizer/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='customizer.demosession')),
            ],
        ),
        migrations.AddIndex(
            model_name='demosession',
            index=models.Index(fields=['template', 'session_token'], name='customizer__templat_e63ec2_idx'),
        ),
    ]
