# Generated by Django 6.0.3 on 2026-04-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('category', models.CharField(blank=True, default='general', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='badrway', max_length=100)),
                ('brand_tagline', models.CharField(default='Premium website templates, instantly yours', max_length=300)),
                ('hero_title', models.CharField(default='Launch a stunning website in minutes, not months', max_length=300)),
                ('hero_subtitle', models.TextField(default='Browse thousands of premium templates, customize every pixel with your own data, and preview the final result live — before you pay.')),
                ('stat_templates', models.PositiveIntegerField(default=850)),
                ('stat_customers', models.PositiveIntegerField(default=12400)),
                ('stat_countries', models.PositiveIntegerField(default=92)),
                ('stat_satisfaction', models.PositiveIntegerField(default=99)),
                ('support_email', models.EmailField(default='support@badrway.com', max_length=254)),
                ('support_phone', models.CharField(blank=True, default='+1 (555) 010-0420', max_length=50)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200)),
                ('author_role', models.CharField(blank=True, max_length=200)),
                ('author_company', models.CharField(blank=True, max_length=200)),
                ('avatar_url', models.CharField(blank=True, max_length=500)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('content', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
    ]
