# Generated by Django 6.0.3 on 2026-04-05 07:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('tagline', models.CharField(blank=True, help_text='Short persuasive tagline for category hero', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon_class', models.CharField(blank=True, help_text='Bootstrap icon class e.g. bi-heart-pulse', max_length=80)),
                ('accent_color', models.CharField(default='#6366f1', help_text='Hex color for category accents', max_length=20)),
                ('cover_image', models.CharField(blank=True, help_text='URL or path for hero cover', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('price', models.DecimalField(decimal_places=2, default=49.0, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pricing_tier', models.CharField(choices=[('starter', 'Starter'), ('standard', 'Standard'), ('premium', 'Premium'), ('elite', 'Elite')], default='standard', max_length=20)),
                ('source_dir', models.CharField(blank=True, help_text="Path relative to TEMPLATE_SOURCE_DIR, e.g. 'Animal/animal'", max_length=500)),
                ('entry_file', models.CharField(default='index.html', max_length=200)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='templates/thumbnails/')),
                ('preview_color_1', models.CharField(default='#6366f1', max_length=20)),
                ('preview_color_2', models.CharField(default='#ec4899', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('technologies', models.CharField(blank=True, default='HTML5, CSS3, Bootstrap 5, JavaScript', max_length=300)),
                ('responsive', models.BooleanField(default=True)),
                ('pages_count', models.PositiveIntegerField(default=1)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=4.8, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='catalog.category')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateCustomizationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=100)),
                ('field_label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('image', 'Image Upload'), ('color', 'Color'), ('url', 'URL'), ('email', 'Email'), ('phone', 'Phone')], default='text', max_length=20)),
                ('placeholder', models.CharField(blank=True, max_length=300)),
                ('default_value', models.TextField(blank=True)),
                ('group', models.CharField(default='branding', help_text='UI group: branding, hero, contact, colors, content', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=False)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='catalog.templateitem')),
            ],
            options={
                'ordering': ['group', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TemplateAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('css', 'CSS'), ('js', 'JavaScript'), ('img', 'Image'), ('font', 'Font'), ('other', 'Other')], max_length=10)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='catalog.templateitem')),
            ],
        ),
        migrations.CreateModel(
            name='TemplatePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('file_path', models.CharField(help_text='Relative path within template source dir', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_entry', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='catalog.templateitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TemplateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('section_id', models.CharField(blank=True, help_text='HTML id, class, or selector', max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_customizable', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='catalog.templateitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='templateitem',
            index=models.Index(fields=['category', 'is_active'], name='catalog_tem_categor_e4c815_idx'),
        ),
        migrations.AddIndex(
            model_name='templateitem',
            index=models.Index(fields=['slug'], name='catalog_tem_slug_3263a0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='templatecustomizationfield',
            unique_together={('template', 'field_key')},
        ),
        migrations.AddIndex(
            model_name='templateasset',
            index=models.Index(fields=['template', 'asset_type'], name='catalog_tem_templat_a14a1c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='templatepage',
            unique_together={('template', 'slug')},
        ),
    ]
